[build]
  publish = "src/sentry/static/sentry/dist"

  command = "yarn webpack"

[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/sentry/dist/*"
  to = "/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "https://www.cylog.org/headers/"
  status = 200
  force = false
  signed = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
